<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { getApiBaseUrl } from '@/config/api'
import AdminSidebar from '@/components/admin/AdminSidebar.vue'

type AdminUser = { id: string; email: string; createdAt: string }
const api = getApiBaseUrl()
const users = ref<AdminUser[]>([])
const form = ref({ id: '', email: '', password: '' })
const message = ref('')
const currentUserId = localStorage.getItem('user_id')
function headers() { return { Authorization: `Bearer ${localStorage.getItem('access_token') || ''}`, 'Content-Type': 'application/json' } }
async function loadUsers() { const response = await fetch(`${api}/auth/users`, { headers: headers() }); const data = await response.json() as { users?: AdminUser[]; message?: string }; if (!response.ok) throw new Error(data.message || 'No pudimos cargar los usuarios.'); users.value = data.users || [] }
async function saveUser() { try { const isEdit = Boolean(form.value.id); const response = await fetch(`${api}/auth/users${isEdit ? `/${form.value.id}` : ''}`, { method: isEdit ? 'PATCH' : 'POST', headers: headers(), body: JSON.stringify({ email: form.value.email, password: form.value.password || undefined }) }); const data = await response.json() as { message?: string }; if (!response.ok) throw new Error(data.message || 'No pudimos guardar el usuario.'); form.value = { id: '', email: '', password: '' }; message.value = 'Usuario guardado correctamente.'; await loadUsers() } catch (error) { message.value = error instanceof Error ? error.message : 'No pudimos guardar el usuario.' } }
function editUser(user: AdminUser) { form.value = { id: user.id, email: user.email, password: '' }; message.value = '' }
async function deleteUser(user: AdminUser) { if (user.id === currentUserId) { message.value = 'No puedes eliminar tu propio usuario.'; return } if (!window.confirm(`¿Eliminar ${user.email}?`)) return; try { const response = await fetch(`${api}/auth/users/${user.id}`, { method: 'DELETE', headers: headers() }); if (!response.ok) { const data = await response.json() as { message?: string }; throw new Error(data.message || 'No pudimos eliminar el usuario.') } message.value = 'Usuario eliminado.'; await loadUsers() } catch (error) { message.value = error instanceof Error ? error.message : 'No pudimos eliminar el usuario.' } }
onMounted(() => { void loadUsers().catch((error) => { message.value = error instanceof Error ? error.message : 'No pudimos cargar los usuarios.' }) })
</script>

<template>
  <main class="users"><AdminSidebar active="users" /><header><RouterLink to="/admin"><i class="fa-solid fa-arrow-left"></i> Volver al portal</RouterLink><h1>Usuarios del portal</h1></header><section class="user-form"><p>{{ form.id ? 'EDITAR USUARIO' : 'CREAR USUARIO' }}</p><form @submit.prevent="saveUser"><label>Correo administrador<input v-model.trim="form.email" required type="email" placeholder="admin@empresa.com"></label><label>Contraseña {{ form.id ? '(dejar vacía para no cambiar)' : '' }}<input v-model="form.password" :required="!form.id" type="password" minlength="8" placeholder="Mínimo 8 caracteres"></label><div class="form-actions"><button>{{ form.id ? 'Guardar cambios' : 'Crear usuario' }}</button><button v-if="form.id" class="cancel" type="button" @click="form = { id: '', email: '', password: '' }">Cancelar</button></div></form><small v-if="message">{{ message }}</small></section><section class="users-list"><h2>Administradores</h2><article v-for="user in users" :key="user.id"><div><b>{{ user.email }}</b><span>{{ user.id === currentUserId ? 'Tu usuario actual' : `Creado ${new Date(user.createdAt).toLocaleDateString('es-EC')}` }}</span></div><div class="user-actions"><button @click="editUser(user)"><i class="fa-solid fa-pen"></i> Editar</button><button class="delete" :disabled="user.id === currentUserId" @click="deleteUser(user)"><i class="fa-solid fa-trash"></i> Eliminar</button></div></article></section></main>
</template>

<style scoped lang="scss">
.users { --ink:#1D1D1B;--cream:#fbf7f2;--pink:#F1B9A9;--pink-soft:#F9E3DC;--gray:#55565A;--copper:#b86f54;background:var(--cream);color:var(--ink);font-family:Arial,sans-serif;min-height:100vh;padding:45px 7vw }@media (min-width:1025px) { .users { padding:44px 48px 60px 328px }.users>header { align-items:baseline;gap:26px;justify-content:flex-start }.users>header,.user-form,.users-list { margin-left:0;margin-right:0;max-width:none } }.users>header { align-items:end;display:flex;justify-content:space-between;margin:auto;max-width:1000px }.users>header a { color:var(--ink);font:600 11px Arial,sans-serif;letter-spacing:.06em;text-decoration:none;text-transform:uppercase }.users h1 { font:600 52px/.9 Georgia,serif;letter-spacing:-.07em;margin:0 }.user-form,.users-list { background:#fffdfa;margin:36px auto 0;max-width:1000px;padding:30px }.user-form>p { color:var(--copper);font:600 10px Arial,sans-serif;letter-spacing:.1em }.user-form form { display:flex;flex-direction:column;gap:16px;margin-top:20px;max-width:560px }.user-form label { display:flex;flex-direction:column;font-size:12px;gap:7px }.user-form input { border:1px solid #bcaeaa;font:14px Arial,sans-serif;padding:13px }.form-actions,.user-actions { display:flex;gap:10px }.user-form button,.users-list button { background:var(--ink);border:0;color:var(--cream);cursor:pointer;font:600 11px Arial,sans-serif;letter-spacing:.05em;padding:13px 15px;text-transform:uppercase }.user-form .cancel,.users-list .delete { background:transparent;border:1px solid #a33d34;color:#a33d34 }.users-list h2 { font:600 28px Georgia,serif;margin:0 0 20px }.users-list article { align-items:center;border-top:1px solid #e3d7d1;display:flex;justify-content:space-between;padding:16px 0 }.users-list article>div:first-child { display:flex;flex-direction:column;gap:5px }.users-list article span { color:#77787B;font-size:11px }.users-list button:disabled { cursor:not-allowed;opacity:.35 }.user-form small { color:#a33d34;display:block;margin-top:14px }@media (max-width:650px) { .users { padding:28px 18px }.users>header { align-items:start;flex-direction:column;gap:20px }.users h1 { font-size:42px }.user-form,.users-list { padding:22px }.users-list article { align-items:stretch;flex-direction:column;gap:14px }.form-actions,.user-actions { flex-direction:column }.form-actions button,.user-actions button { width:100% } }
</style>
